name: paraview
version: '5.3.0'
summary: ParaView 5.3.1 Qt5 OpenGL2
description: |
  ParaView is an open-source, multi-platform data analysis
  and visualization application. ParaView users can quickly
  build visualizations to analyze their data using qualitative
  and quantitative techniques. The data exploration can be done
  interactively in 3D or programmatically using ParaView’s batch
  processing capabilities.
grade: stable
confinement: strict

apps:
  paraview:
    command: desktop-launch $SNAP/bin/paraview
    plugs:
      - x11
      - opengl
      - unity7
      - home
      - network
      - network-bind
  pvbatch:
    command: bin/pvbatch
    plugs:
      - x11
      - opengl
      - home
      - network
      - network-bind
  pvserver:
    command: bin/pvserver
    plugs:
      - x11
      - opengl
      - home
      - network
      - network-bind
  pvdataserver:
    command: bin/pvdataserver
    plugs:
      - x11
      - opengl
      - home
      - network
      - network-bind
  pvrenderserver:
    command: bin/pvrenderserver
    plugs:
      - x11
      - opengl
      - home
      - network
      - network-bind
  pvpython:
    command: bin/pvpython
    plugs:
      - x11
      - opengl
      - home
      - network
      - network-bind
  mpiexec:
    command: bin/mpiexec
    plugs:
      - home
      - network
      - network-bind

parts:
  paraview:
    source: http://www.paraview.org/paraview-downloads/download.php?submit=Download&version=v5.3&type=binary&os=linux64&downloadFile=ParaView-5.3.0-Qt5-OpenGL2-MPI-Linux-64bit.tar.gz
    plugin: dump
    stage-packages:
      - libsm6
      - libxt6
    after:
      - desktop-qt5
